### ISSUE TITLE
Issues when trying to contribute

### ISSUE THREAD

**Issue by dawsonbotsford** [steven2358/BitcoinSneakPeek#8]
I know how to listen on the DOM and therefore fix issue #2, but when loading the src locally I get ```Uncaught TypeError: Cannot read property 'nodeType' of nullwalk @ content_script.js:17```.

Can you help me figure this out so that we can contribute to the extension as a community?

Cheers

**Comment by steven2358** [comment]
I cannot replicate this error. Does it really say "nullwalk"? Google is not helping much on "nullwalk".

**Comment by dawsonbotsford** [comment]
Must have been a collision of other extensions. Locally things are working now. Expect a PR with solution to #2 in the near future. 
Nice project by the way. Cheers.

**Comment by steven2358** [comment]
Sounds good, thanks.
